version: "3.8"
services:
  frontend:
    build:
      context: .
    command: yarn start
    environment:
      BROWSER: none
      HOST: 0.0.0.0
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
